### ISSUE TITLE
E/AudioplayersPlugin( 9255): Unexpected error!

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#125]
```
MediaPlayer( 9255): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 9255): cleanDrmObj: mDrmObj=null mDrmSessionId=null
I/flutter ( 9255): Tap on (2, 2) <16>
I/flutter ( 9255): putPiece: skip [15]
I/flutter ( 9255): selectPiece: skip [15]
I/flutter ( 9255): Tap on (2, 1) <15>
I/flutter ( 9255): Tap on (0, 4) <4>
I/flutter ( 9255): Tap on (1, 3) <10>
I/flutter ( 9255): O to move.
I/flutter ( 9255): putPiece: [16]
I/flutter ( 9255): Tap on (0, 2) <2>
E/MediaPlayerNative( 9255): attachNewPlayer called in state 8
E/AudioplayersPlugin( 9255): Unexpected error!
E/AudioplayersPlugin( 9255): java.lang.IllegalStateException
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer._setDataSource(Native Method)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1305)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1288)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1242)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1218)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1185)
E/AudioplayersPlugin( 9255): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setSource(WrappedMediaPlayer.java:287)
E/AudioplayersPlugin( 9255): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.java:54)
E/AudioplayersPlugin( 9255): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:65)
E/AudioplayersPlugin( 9255): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:44)
E/AudioplayersPlugin( 9255): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AudioplayersPlugin( 9255): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AudioplayersPlugin( 9255): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AudioplayersPlugin( 9255): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AudioplayersPlugin( 9255): 	at android.os.MessageQueue.next(MessageQueue.java:332)
E/AudioplayersPlugin( 9255): 	at android.os.Looper.loop(Looper.java:168)
E/AudioplayersPlugin( 9255): 	at android.app.ActivityThread.main(ActivityThread.java:6878)
E/AudioplayersPlugin( 9255): 	at java.lang.reflect.Method.invoke(Native Method)
E/AudioplayersPlugin( 9255): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AudioplayersPlugin( 9255): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
E/MediaPlayerNative( 9255): attachNewPlayer called in state 8
E/AudioplayersPlugin( 9255): Unexpected error!
E/AudioplayersPlugin( 9255): java.lang.IllegalStateException
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer._setDataSource(Native Method)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1305)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1288)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1242)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1218)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1185)
E/AudioplayersPlugin( 9255): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setSource(WrappedMediaPlayer.java:287)
E/AudioplayersPlugin( 9255): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.java:54)
E/AudioplayersPlugin( 9255): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:65)
E/AudioplayersPlugin( 9255): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:44)
E/AudioplayersPlugin( 9255): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AudioplayersPlugin( 9255): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AudioplayersPlugin( 9255): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AudioplayersPlugin( 9255): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AudioplayersPlugin( 9255): 	at android.os.MessageQueue.next(MessageQueue.java:332)
E/AudioplayersPlugin( 9255): 	at android.os.Looper.loop(Looper.java:168)
E/AudioplayersPlugin( 9255): 	at android.app.ActivityThread.main(ActivityThread.java:6878)
E/AudioplayersPlugin( 9255): 	at java.lang.reflect.Method.invoke(Native Method)
E/AudioplayersPlugin( 9255): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AudioplayersPlugin( 9255): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
E/MediaPlayerNative( 9255): pause called in state 8, mPlayer(0x7aa8429280)
E/MediaPlayerNative( 9255): error (-38, 0)
E/MediaPlayerNative( 9255): invoke failed: wrong state 0, mPlayer(0x7aa8429280)
E/MediaPlayerNative( 9255): Attempt to call getDuration in wrong state: mPlayer=0x7aa8429280, mCurrentState=0
E/MediaPlayerNative( 9255): error (-38, 0)
E/MediaPlayerNative( 9255): start called in state 0, mPlayer(0x7aa8429280)
E/MediaPlayerNative( 9255): error (-38, 0)
E/MediaPlayerNative( 9255): Attempt to perform seekTo in wrong state: mPlayer=0x7aa8429280, mCurrentState=0
E/MediaPlayerNative( 9255): error (-38, 0)
E/MediaPlayerNative( 9255): pause called in state 0, mPlayer(0x7aa8429280)
E/MediaPlayerNative( 9255): error (-38, 0)
E/MediaPlayerNative( 9255): Attempt to perform seekTo in wrong state: mPlayer=0x7aa8429280, mCurrentState=0
E/MediaPlayerNative( 9255): error (-38, 0)
E/MediaPlayerNative( 9255): Attempt to perform seekTo in wrong state: mPlayer=0x7aa8429280, mCurrentState=0
E/MediaPlayerNative( 9255): error (-38, 0)
E/MediaPlayer( 9255): Error (-38,0)
V/MediaPlayer( 9255): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 9255): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 9255): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 9255): cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/System  ( 9255): A resource failed to call close. 
W/System  ( 9255): A resource failed to call close. 
I/flutter ( 9255): Tap on (4, 2) <30>
I/flutter ( 9255): @ to move.
I/flutter ( 9255): putPiece: [13]
I/flutter ( 9255): Tap on (2, 1) <15>
E/MediaPlayerNative( 9255): attachNewPlayer called in state 4
E/AudioplayersPlugin( 9255): Unexpected error!
E/AudioplayersPlugin( 9255): java.lang.IllegalStateException
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer._setDataSource(Native Method)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1305)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1288)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1242)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1218)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1185)
E/AudioplayersPlugin( 9255): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setSource(WrappedMediaPlayer.java:287)
E/AudioplayersPlugin( 9255): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.java:54)
E/AudioplayersPlugin( 9255): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:65)
E/AudioplayersPlugin( 9255): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:44)
E/AudioplayersPlugin( 9255): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AudioplayersPlugin( 9255): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AudioplayersPlugin( 9255): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AudioplayersPlugin( 9255): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AudioplayersPlugin( 9255): 	at android.os.MessageQueue.next(MessageQueue.java:332)
E/AudioplayersPlugin( 9255): 	at android.os.Looper.loop(Looper.java:168)
E/AudioplayersPlugin( 9255): 	at android.app.ActivityThread.main(ActivityThread.java:6878)
E/AudioplayersPlugin( 9255): 	at java.lang.reflect.Method.invoke(Native Method)
E/AudioplayersPlugin( 9255): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AudioplayersPlugin( 9255): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
E/MediaPlayerNative( 9255): attachNewPlayer called in state 8
E/AudioplayersPlugin( 9255): Unexpected error!
E/AudioplayersPlugin( 9255): java.lang.IllegalStateException
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer._setDataSource(Native Method)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1305)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1288)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1242)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1218)
E/AudioplayersPlugin( 9255): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1185)
E/AudioplayersPlugin( 9255): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setSource(WrappedMediaPlayer.java:287)
E/AudioplayersPlugin( 9255): 	at xyz.luan.audioplayers.WrappedMediaPlayer.setUrl(WrappedMediaPlayer.java:54)
E/AudioplayersPlugin( 9255): 	at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:65)
E/AudioplayersPlugin( 9255): 	at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:44)
E/AudioplayersPlugin( 9255): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AudioplayersPlugin( 9255): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AudioplayersPlugin( 9255): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AudioplayersPlugin( 9255): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AudioplayersPlugin( 9255): 	at android.os.MessageQueue.next(MessageQueue.java:332)
E/AudioplayersPlugin( 9255): 	at android.os.Looper.loop(Looper.java:168)
E/AudioplayersPlugin( 9255): 	at android.app.ActivityThread.main(ActivityThread.java:6878)
E/AudioplayersPlugin( 9255): 	at java.lang.reflect.Method.invoke(Native Method)
E/AudioplayersPlugin( 9255): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AudioplayersPlugin( 9255): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
V/MediaPlayer( 9255): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 9255): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer( 9255): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer( 9255): cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/System  ( 9255): A resource failed to call close. 
W/System  ( 9255): A resource failed to call close. 
```

**Comment by calcitem** [comment]
chang plugin
