### ISSUE TITLE
 Cannot create file, path = './sanmill-crash-logs.txt' (OS Error: Read-only file system, errno = 30) stack: #0 

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#146]
```
/flutter (23149): [2021-03-13 22:53:53.322492 | FileHandler | INFO] Exception occured: FileSystemException: Cannot create file, path = './sanmill-crash-logs.txt' (OS Error: Read-only file system, errno = 30) stack: #0      _File.throwIfError (dart:io/file_impl.dart:635:7)
I/flutter (23149): #1      _File.createSync (dart:io/file_impl.dart:273:5)
I/flutter (23149): #2      FileHandler._checkFile (package:catcher/handlers/file_handler.dart:60:14)
I/flutter (23149): <asynchronous suspension>
I/flutter (23149): #3      FileHandler.handle (package:catcher/handlers/file_handler.dart:35:33)
I/flutter (23149): <asynchronous suspension>
I/flutter (23149): #4      Future.timeout.<anonymous closure> (dart:async/future_impl.dart)
I/flutter (23149): <asynchronous suspension>
```

**Comment by calcitem** [comment]
解决了
