### ISSUE TITLE
偶然变得很慢导致超时

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#149]
偶然引擎返回变得很慢导致超时。
退出后，首次进入必现。点 new 后再下没问题。
如下log，规则设置12子，传递却是9子，异常。

```
Launching lib\main.dart on AOSP on redfin in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Debug service listening on ws://127.0.0.1:51771/SyWB945JMAs=/ws
Syncing files to device AOSP on redfin...
I/flutter (25296): [2021-03-27 21:44:34.488545 | Catcher | FINE] Using debug config
I/flutter (25296): [2021-03-27 21:44:34.760517 | Catcher | WARNING] Screenshots path is empty. Screenshots won't work.
I/flutter (25296): [2021-03-27 21:44:34.776967 | Catcher | FINE] Catcher configured successfully.
I/flutter (25296): Engine type: EngineType.humanVsAi
I/flutter (25296): Game Page didPush route: /
D/MillEngine(25296): println: uciok
I/flutter (25296): send: setoption name SkillLevel value 20
D/MillEngine(25296): [uci] input: uci
D/MillEngine(25296): [uci] input: setoption name SkillLevel value 20
E/flutter (25296): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
E/flutter (25296): #0      new List.from (dart:core-patch/array_patch.dart:40:5)
E/flutter (25296): #1      AndroidDeviceInfo._fromList (package:device_info_plus_platform_interface/model/android_device_info.dart:144:12)
E/flutter (25296): #2      AndroidDeviceInfo.fromMap (package:device_info_plus_platform_interface/model/android_device_info.dart:137:23)
E/flutter (25296): #3      MethodChannelDeviceInfo.androidInfo (package:device_info_plus_platform_interface/method_channel/method_channel_device_info.dart:19:30)
E/flutter (25296): <asynchronous suspension>
E/flutter (25296): #4      DeviceInfoPlugin.androidInfo (package:device_info_plus/device_info_plus.dart:65:36)
E/flutter (25296): <asynchronous suspension>
E/flutter (25296): #5      Catcher._loadDeviceInfo.<anonymous closure> (package:catcher/core/catcher.dart)
E/flutter (25296): <asynchronous suspension>
E/flutter (25296): 
I/flutter (25296): ExternalStorageDirectory: /storage/emulated/0/Android/data/com.calcitem.sanmill/files
I/flutter (25296): [2021-03-27 21:44:36.126311 | Catcher | FINE] Using debug config
I/flutter (25296): [2021-03-27 21:44:36.126565 | Catcher | WARNING] Screenshots path is empty. Screenshots won't work.
I/flutter (25296): {ToneEnabled: true, ThinkingTime: 10000, AiMovesFirst: false, AiIsLazy: false, SkillLevel: 20, IsAutoRestart: true, IsAutoChangeFirstMove: false, ResignIfMostLose: false, ShufflingEnabled: true, LearnEndgame: false, IdsEnabled: false, DepthExtension: false, OpeningBook: false, IsPieceCountInHandShown: false, BoardBorderLineWidth: 2.0, BoardInnerLineWidth: 2.0, BoardLineColor: 2574057485, DarkBackgroundColor: 4279655217, BoardBackgroundColor: 4292786311, BlackPieceColor: 4278190080, WhitePieceColor: 4294967295, PiecesCount: 12, PiecesAtLeastCount: 3, HasDiagonalLines: false, HasBannedLocations: false, IsDefenderMoveFirst: true, MayRemoveMultiple: false, MayRemoveFromMillsAlways: true, IsBlackLoseButNotDrawWhenBoardFull: false, IsLoseButNotChangeSideWhenNoWay: true, MayFly: true, MaxStepsLedToDraw: 50}
I/flutter (25296): defaultFileName: settings.json
I/flutter (25296): send: setoption name AiIsLazy value false
D/MillEngine(25296): [uci] input: setoption name AiIsLazy value false
I/flutter (25296): send: setoption name Shuffling value true
D/MillEngine(25296): [uci] input: setoption name Shuffling value true
I/flutter (25296): send: setoption name PiecesCount value 12
D/MillEngine(25296): [uci] input: setoption name PiecesCount value 12
I/flutter (25296): send: setoption name PiecesAtLeastCount value 3
I/flutter (25296): send: setoption name HasDiagonalLines value false
D/MillEngine(25296): [uci] input: setoption name PiecesAtLeastCount value 3
I/flutter (25296): send: setoption name HasBannedLocations value false
D/MillEngine(25296): [uci] input: setoption name HasDiagonalLines value false
I/flutter (25296): send: setoption name IsDefenderMoveFirst value true
D/MillEngine(25296): [uci] input: setoption name HasBannedLocations value false
I/flutter (25296): send: setoption name MayRemoveMultiple value false
D/MillEngine(25296): [uci] input: setoption name IsDefenderMoveFirst value true
D/MillEngine(25296): [uci] input: setoption name MayRemoveMultiple value false
I/flutter (25296): send: setoption name MayRemoveFromMillsAlways value true
I/flutter (25296): send: setoption name IsBlackLoseButNotDrawWhenBoardFull value false
D/MillEngine(25296): [uci] input: setoption name MayRemoveFromMillsAlways value true
D/MillEngine(25296): [uci] input: setoption name IsBlackLoseButNotDrawWhenBoardFull value false
I/flutter (25296): send: setoption name IsLoseButNotChangeSideWhenNoWay value true
D/MillEngine(25296): [uci] input: setoption name IsLoseButNotChangeSideWhenNoWay value true
I/flutter (25296): send: setoption name MayFly value true
D/MillEngine(25296): [uci] input: setoption name MayFly value true
I/flutter (25296): send: setoption name MaxStepsLedToDraw value 50
D/MillEngine(25296): [uci] input: setoption name MaxStepsLedToDraw value 50
I/flutter (25296): Tap on (5, 1) <36>
I/flutter (25296): O to move.
I/flutter (25296): putPiece: [21]
I/flutter (25296): Engine to go
I/flutter (25296): Waiting for engine's response...
I/flutter (25296): posFenStr: position fen ********/********/******** b p p 0 9 0 9 0 0 1 moves (2,6)
I/flutter (25296): send: position fen ********/********/******** b p p 0 9 0 9 0 0 1 moves (2,6)
I/flutter (25296): send: go
D/MillEngine(25296): [uci] input: position fen ********/********/******** b p p 0 9 0 9 0 0 1 moves (2,6)
D/MillEngine(25296): [uci] input: go
I/TetheringManager(25296): registerTetheringEventCallback:com.calcitem.sanmill
W/alcitem.sanmil(25296): Accessing hidden method Landroid/media/AudioTrack;->getLatency()I (greylist, reflection, allowed)
I/ExoPlayerImpl(25296): Init 1e2d843 [ExoPlayerLib/2.13.1] [redfin, AOSP on redfin, Google, 30]
W/VideoCapabilities(25296): Unrecognized level 1879048707 for video/x-vnd.on2.vp8
W/VideoCapabilities(25296): Unrecognized profile 1879048704 for video/x-vnd.on2.vp8
W/VideoCapabilities(25296): Unrecognized level 1879048707 for video/x-vnd.on2.vp8
W/VideoCapabilities(25296): Unrecognized profile 1879048704 for video/x-vnd.on2.vp8
W/VideoCapabilities(25296): Unsupported mime image/vnd.android.heic
W/VideoCapabilities(25296): Unrecognized level 1879048707 for video/x-vnd.on2.vp8
W/VideoCapabilities(25296): Unrecognized profile 1879048704 for video/x-vnd.on2.vp8
W/VideoCapabilities(25296): Unrecognized level 1879048707 for video/x-vnd.on2.vp8
W/VideoCapabilities(25296): Unrecognized profile 1879048704 for video/x-vnd.on2.vp8
D/CCodec  (25296): allocate(c2.android.mp3.decoder)
I/Codec2Client(25296): Available Codec2 services: "default" "software"
I/CCodec  (25296): setting up 'default' as default (vendor) store
I/CCodec  (25296): Created component [c2.android.mp3.decoder]
D/CCodecConfig(25296): read media type: audio/mpeg
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig(25296): query failed after returning 7 values (BAD_INDEX)
D/CCodecConfig(25296): c2 config diff is Dict {
D/CCodecConfig(25296):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig(25296):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig(25296):   c2::u32 input.delay.value = 0
D/CCodecConfig(25296):   string input.media-type.value = "audio/mpeg"
D/CCodecConfig(25296):   string output.media-type.value = "audio/raw"
D/CCodecConfig(25296):   c2::u32 raw.channel-count.value = 2
D/CCodecConfig(25296):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig(25296): }
D/CCodec  (25296): [c2.android.mp3.decoder] buffers are bound to CCodec for this session
D/CCodecConfig(25296): no c2 equivalents for flags
D/CCodecConfig(25296): config failed => CORRUPTED
D/CCodecConfig(25296): c2 config diff is   c2::u32 raw.channel-count.value = 1
W/Codec2Client(25296): query -- param skipped: index = 1107298332.
D/CCodec  (25296): client requested max input size 4096, which is smaller than what component recommended (8192); overriding with component recommendation.
W/CCodec  (25296): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  (25296): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (25296):   int32_t channel-count = 1
D/CCodec  (25296):   int32_t max-input-size = 8192
D/CCodec  (25296):   string mime = "audio/mpeg"
D/CCodec  (25296):   int32_t sample-rate = 44100
D/CCodec  (25296): } and output: AMessage(what = 0x00000000) = {
D/CCodec  (25296):   int32_t channel-count = 1
D/CCodec  (25296):   string mime = "audio/raw"
D/CCodec  (25296):   int32_t sample-rate = 44100
D/CCodec  (25296): }
W/Codec2Client(25296): query -- param skipped: index = 1342179345.
W/Codec2Client(25296): query -- param skipped: index = 2415921170.
E/FMQ     (25296): grantorIdx must be less than 3
E/FMQ     (25296): grantorIdx must be less than 3
D/CCodecBufferChannel(25296): [c2.android.mp3.decoder#780] Created input block pool with allocatorID 16 => poolID 17 - OK (0)
I/CCodecBufferChannel(25296): [c2.android.mp3.decoder#780] Created output block pool with allocatorID 16 => poolID 974 - OK
D/CCodecBufferChannel(25296): [c2.android.mp3.decoder#780] Configured output block pool ids 974 => OK
E/ion     (25296): ioctl c0044901 failed with code -1: Inappropriate ioctl for device
E/FMQ     (25296): grantorIdx must be less than 3
E/FMQ     (25296): grantorIdx must be less than 3
D/CCodecBuffers(25296): [c2.android.mp3.decoder#780:Output[N]] popFromStashAndRegister: output format changed to AMessage(what = 0x00000000) = {
D/CCodecBuffers(25296):   int32_t channel-count = 1
D/CCodecBuffers(25296):   string mime = "audio/raw"
D/CCodecBuffers(25296):   int32_t sample-rate = 44100
D/CCodecBuffers(25296): }
D/AudioTrack(25296): getTimestamp_l(835): device stall time corrected using current time 61139290103434
D/AudioTrack(25296): stop(835): called with 27072 frames delivered
D/MillEngine(25296): println: bestmove (2,7)
I/flutter (25296): response: bestmove (2,7)
I/flutter (25296): Engine response type: move
I/flutter (25296): Computer: (2,7)
I/flutter (25296): @ to move.
I/flutter (25296): Score: 0 : 0 : 0	total: 0
I/flutter (25296): 0.0% : 0.0% : 0.0%
I/ExoPlayerImpl(25296): Release 1e2d843 [ExoPlayerLib/2.13.1] [redfin, AOSP on redfin, Google, 30] [goog.exo.core]
I/CCodecConfig(25296): query failed after returning 7 values (BAD_INDEX)
W/Codec2Client(25296): query -- param skipped: index = 1342179345.
W/Codec2Client(25296): query -- param skipped: index = 2415921170.
D/CCodecBufferChannel(25296): [c2.android.mp3.decoder#780] MediaCodec discarded an unknown buffer
I/chatty  (25296): uid=10164(com.calcitem.sanmill) identical 2 lines
D/CCodecBufferChannel(25296): [c2.android.mp3.decoder#780] MediaCodec discarded an unknown buffer
I/hw-BpHwBinder(25296): onLastStrongRef automatically unlinking death recipients
I/ExoPlayerImpl(25296): Init 10e7c16 [ExoPlayerLib/2.13.1] [redfin, AOSP on redfin, Google, 30]
D/CCodec  (25296): allocate(c2.android.mp3.decoder)
I/CCodec  (25296): setting up 'default' as default (vendor) store
I/CCodec  (25296): Created component [c2.android.mp3.decoder]
D/CCodecConfig(25296): read media type: audio/mpeg
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig(25296): query failed after returning 7 values (BAD_INDEX)
D/CCodecConfig(25296): c2 config diff is Dict {
D/CCodecConfig(25296):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig(25296):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig(25296):   c2::u32 input.delay.value = 0
D/CCodecConfig(25296):   string input.media-type.value = "audio/mpeg"
D/CCodecConfig(25296):   string output.media-type.value = "audio/raw"
D/CCodecConfig(25296):   c2::u32 raw.channel-count.value = 2
D/CCodecConfig(25296):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig(25296): }
D/CCodec  (25296): [c2.android.mp3.decoder] buffers are bound to CCodec for this session
D/CCodecConfig(25296): no c2 equivalents for flags
D/CCodecConfig(25296): config failed => CORRUPTED
D/CCodecConfig(25296): c2 config diff is   c2::u32 raw.channel-count.value = 1
W/Codec2Client(25296): query -- param skipped: index = 1107298332.
D/CCodec  (25296): client requested max input size 4096, which is smaller than what component recommended (8192); overriding with component recommendation.
W/CCodec  (25296): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  (25296): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (25296):   int32_t channel-count = 1
D/CCodec  (25296):   int32_t max-input-size = 8192
D/CCodec  (25296):   string mime = "audio/mpeg"
D/CCodec  (25296):   int32_t sample-rate = 44100
D/CCodec  (25296): } and output: AMessage(what = 0x00000000) = {
D/CCodec  (25296):   int32_t channel-count = 1
D/CCodec  (25296):   string mime = "audio/raw"
D/CCodec  (25296):   int32_t sample-rate = 44100
D/CCodec  (25296): }
W/Codec2Client(25296): query -- param skipped: index = 1342179345.
W/Codec2Client(25296): query -- param skipped: index = 2415921170.
E/FMQ     (25296): grantorIdx must be less than 3
E/FMQ     (25296): grantorIdx must be less than 3
D/CCodecBufferChannel(25296): [c2.android.mp3.decoder#730] Created input block pool with allocatorID 16 => poolID 18 - OK (0)
I/CCodecBufferChannel(25296): [c2.android.mp3.decoder#730] Created output block pool with allocatorID 16 => poolID 975 - OK
D/CCodecBufferChannel(25296): [c2.android.mp3.decoder#730] Configured output block pool ids 975 => OK
E/FMQ     (25296): grantorIdx must be less than 3
E/FMQ     (25296): grantorIdx must be less than 3
D/CCodecBuffers(25296): [c2.android.mp3.decoder#730:Output[N]] popFromStashAndRegister: output format changed to AMessage(what = 0x00000000) = {
D/CCodecBuffers(25296):   int32_t channel-count = 1
D/CCodecBuffers(25296):   string mime = "audio/raw"
D/CCodecBuffers(25296):   int32_t sample-rate = 44100
D/CCodecBuffers(25296): }
D/AudioTrack(25296): getTimestamp_l(836): device stall time corrected using current time 61144161171888
D/AudioTrack(25296): stop(836): called with 27072 frames delivered
I/flutter (25296): Tap on (5, 5) <40>
I/flutter (25296): O to move.
I/flutter (25296): putPiece: [19]
I/flutter (25296): Engine to go
I/flutter (25296): Waiting for engine's response...
I/flutter (25296): posFenStr: position fen ********/********/******** b p p 0 9 0 9 0 0 1 moves (2,6) (2,7) (2,4)
I/ExoPlayerImpl(25296): Release 10e7c16 [ExoPlayerLib/2.13.1] [redfin, AOSP on redfin, Google, 30] [goog.exo.core]
I/flutter (25296): send: position fen ********/********/******** b p p 0 9 0 9 0 0 1 moves (2,6) (2,7) (2,4)
I/flutter (25296): send: go
I/CCodecConfig(25296): query failed after returning 7 values (BAD_INDEX)
W/Codec2Client(25296): query -- param skipped: index = 1342179345.
W/Codec2Client(25296): query -- param skipped: index = 2415921170.
D/CCodecBufferChannel(25296): [c2.android.mp3.decoder#730] MediaCodec discarded an unknown buffer
I/chatty  (25296): uid=10164(com.calcitem.sanmill) identical 2 lines
D/CCodecBufferChannel(25296): [c2.android.mp3.decoder#730] MediaCodec discarded an unknown buffer
I/hw-BpHwBinder(25296): onLastStrongRef automatically unlinking death recipients
D/MillEngine(25296): [uci] input: position fen ********/********/******** b p p 0 9 0 9 0 0 1 moves (2,6) (2,7) (2,4)
D/MillEngine(25296): [uci] input: go
I/ExoPlayerImpl(25296): Init dd8448f [ExoPlayerLib/2.13.1] [redfin, AOSP on redfin, Google, 30]
D/CCodec  (25296): allocate(c2.android.mp3.decoder)
I/CCodec  (25296): setting up 'default' as default (vendor) store
I/CCodec  (25296): Created component [c2.android.mp3.decoder]
D/CCodecConfig(25296): read media type: audio/mpeg
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: algo.buffers.max-count.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: output.subscribed-indices.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: input.buffers.allocator-ids.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: output.buffers.allocator-ids.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: algo.buffers.allocator-ids.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: output.buffers.pool-ids.values
D/ReflectedParamUpdater(25296): extent() != 1 for single value type: algo.buffers.pool-ids.values
I/CCodecConfig(25296): query failed after returning 7 values (BAD_INDEX)
D/CCodecConfig(25296): c2 config diff is Dict {
D/CCodecConfig(25296):   c2::u32 coded.bitrate.value = 64000
D/CCodecConfig(25296):   c2::u32 input.buffers.max-size.value = 8192
D/CCodecConfig(25296):   c2::u32 input.delay.value = 0
D/CCodecConfig(25296):   string input.media-type.value = "audio/mpeg"
D/CCodecConfig(25296):   string output.media-type.value = "audio/raw"
D/CCodecConfig(25296):   c2::u32 raw.channel-count.value = 2
D/CCodecConfig(25296):   c2::u32 raw.sample-rate.value = 44100
D/CCodecConfig(25296): }
D/CCodec  (25296): [c2.android.mp3.decoder] buffers are bound to CCodec for this session
D/CCodecConfig(25296): no c2 equivalents for flags
D/CCodecConfig(25296): config failed => CORRUPTED
D/CCodecConfig(25296): c2 config diff is   c2::u32 raw.channel-count.value = 1
W/Codec2Client(25296): query -- param skipped: index = 1107298332.
D/CCodec  (25296): client requested max input size 4096, which is smaller than what component recommended (8192); overriding with component recommendation.
W/CCodec  (25296): This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.
D/CCodec  (25296): setup formats input: AMessage(what = 0x00000000) = {
D/CCodec  (25296):   int32_t channel-count = 1
D/CCodec  (25296):   int32_t max-input-size = 8192
D/CCodec  (25296):   string mime = "audio/mpeg"
D/CCodec  (25296):   int32_t sample-rate = 44100
D/CCodec  (25296): } and output: AMessage(what = 0x00000000) = {
D/CCodec  (25296):   int32_t channel-count = 1
D/CCodec  (25296):   string mime = "audio/raw"
D/CCodec  (25296):   int32_t sample-rate = 44100
D/CCodec  (25296): }
W/Codec2Client(25296): query -- param skipped: index = 1342179345.
W/Codec2Client(25296): query -- param skipped: index = 2415921170.
E/FMQ     (25296): grantorIdx must be less than 3
E/FMQ     (25296): grantorIdx must be less than 3
D/CCodecBufferChannel(25296): [c2.android.mp3.decoder#270] Created input block pool with allocatorID 16 => poolID 19 - OK (0)
I/CCodecBufferChannel(25296): [c2.android.mp3.decoder#270] Created output block pool with allocatorID 16 => poolID 976 - OK
D/CCodecBufferChannel(25296): [c2.android.mp3.decoder#270] Configured output block pool ids 976 => OK
E/FMQ     (25296): grantorIdx must be less than 3
E/FMQ     (25296): grantorIdx must be less than 3
D/CCodecBuffers(25296): [c2.android.mp3.decoder#270:Output[N]] popFromStashAndRegister: output format changed to AMessage(what = 0x00000000) = {
D/CCodecBuffers(25296):   int32_t channel-count = 1
D/CCodecBuffers(25296):   string mime = "audio/raw"
D/CCodecBuffers(25296):   int32_t sample-rate = 44100
D/CCodecBuffers(25296): }
D/AudioTrack(25296): getTimestamp_l(837): device stall time corrected using current time 61148174320621
D/AudioTrack(25296): stop(837): called with 27072 frames delivered
D/BufferPoolAccessor2.0(25296): bufferpool2 0xb400006f2d405c58 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/48 (fetch/transfer)
D/BufferPoolAccessor2.0(25296): evictor expired: 1, evicted: 1
D/BufferPoolAccessor2.0(25296): bufferpool2 0xb400006f2d42d158 : 0(0 size) total buffers - 0(0 size) used buffers - 0/5 (recycle/alloc) - 4/48 (fetch/transfer)
D/BufferPoolAccessor2.0(25296): bufferpool2 0xb400006f2d45c588 : 5(40960 size) total buffers - 4(32768 size) used buffers - 0/5 (recycle/alloc) - 4/48 (fetch/transfer)
D/BufferPoolAccessor2.0(25296): evictor expired: 2, evicted: 2
I/flutter (25296): response: 
I/flutter (25296): Engine response type: timeout
I/flutter (25296): [2021-03-27 21:44:58.500193 | Catcher | INFO] Setup localization lazily!
I/flutter (25296): Game Page didPushNext route: /
I/flutter (25296): send: setoption name SkillLevel value 20
D/MillEngine(25296): [uci] input: setoption name SkillLevel value 20
I/flutter (25296): send: setoption name AiIsLazy value false
D/MillEngine(25296): [uci] input: setoption name AiIsLazy value false
I/flutter (25296): send: setoption name Shuffling value true
D/MillEngine(25296): [uci] input: setoption name Shuffling value true
I/flutter (25296): send: setoption name PiecesCount value 12
I/flutter (25296): send: setoption name PiecesAtLeastCount value 3
D/MillEngine(25296): [uci] input: setoption name PiecesCount value 12
D/MillEngine(25296): [uci] input: setoption name PiecesAtLeastCount value 3
I/flutter (25296): send: setoption name HasDiagonalLines value false
I/flutter (25296): send: setoption name HasBannedLocations value false
I/flutter (25296): send: setoption name IsDefenderMoveFirst value true
D/MillEngine(25296): [uci] input: setoption name HasDiagonalLines value false
D/MillEngine(25296): [uci] input: setoption name HasBannedLocations value false
I/flutter (25296): send: setoption name MayRemoveMultiple value false
I/flutter (25296): send: setoption name MayRemoveFromMillsAlways value true
D/MillEngine(25296): [uci] input: setoption name IsDefenderMoveFirst value true
D/MillEngine(25296): [uci] input: setoption name MayRemoveMultiple value false
D/MillEngine(25296): [uci] input: setoption name MayRemoveFromMillsAlways value true
I/flutter (25296): send: setoption name IsBlackLoseButNotDrawWhenBoardFull value false
I/flutter (25296): send: setoption name IsLoseButNotChangeSideWhenNoWay value true
D/MillEngine(25296): [uci] input: setoption name IsBlackLoseButNotDrawWhenBoardFull value false
I/flutter (25296): send: setoption name MayFly value true
D/MillEngine(25296): [uci] input: setoption name IsLoseButNotChangeSideWhenNoWay value true
I/flutter (25296): send: setoption name MaxStepsLedToDraw value 50
D/MillEngine(25296): [uci] input: setoption name MayFly value true
D/MillEngine(25296): [uci] input: setoption name MaxStepsLedToDraw value 50
D/MillEngine(25296): println: bestmove (2,5)
```

**Comment by calcitem** [comment]
刚解决
