### ISSUE TITLE
Unsupported operation: Infinity or NaN toInt

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#205]
```
Error:

Unsupported operation: Infinity or NaN toInt

Stack trace:

#0 _Double.toInt (dart:core-patch/double.dart:219)
#1 _BoxEdge.compareTo (package:flutter/src/semantics/semantics.dart:2328)
#2 Comparable.compare (dart:core/comparable.dart:88)
#3 ListMixin._compareAny (dart:collection/list.dart:359)
#4 Sort._insertionSort (dart:_internal/sort.dart:69)
#5 Sort._doSort (dart:_internal/sort.dart:58)
#6 Sort.sort (dart:_internal/sort.dart:33)
#7 ListMixin.sort (dart:collection/list.dart:355)
#8 _childrenInDefaultOrder (package:flutter/src/semantics/semantics.dart:2523)
#9 SemanticsNode._childrenInTraversalOrder (package:flutter/src/semantics/semantics.dart:2117)
#10 SemanticsNode._addToUpdate (package:flutter/src/semantics/semantics.dart:2055)
#11 SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:2653)
#12 PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1083)
#13 RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:458)
#14 WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:874)
#15 RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319)
#16 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144)
#17 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082)
#18 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998)
#19 _rootRun (dart:async/zone.dart:1354)
#20 _CustomZone.run (dart:async/zone.dart:1258)
#21 _CustomZone.runGuarded (dart:async/zone.dart:1162)
#22 _invoke (dart:ui/hooks.dart:161)
#23 PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253)
#24 _drawFrame (dart:ui/hooks.dart:120)


Device parameters:

manufacturer: samsung
model: SM-G973F
versionSdk: 29

environment: release
version: 1.0.7
appName: Mill
buildNumber: 1813
packageName: com.calcitem.sanmill


Custom parameters:
```

**Comment by calcitem** [comment]
Same Issue: https://github.com/flutter/flutter/issues/77908
