### ISSUE TITLE
buildScope missed some dirty elements.

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#444]
Commit e14545b4f7d41610d2949b35edcd7fe2acdc8355

```
I/flutter (26348): [2021-12-16 01:01:02.558601 | Catcher | INFO] buildScope missed some dirty elements.
I/flutter (26348): This probably indicates that the dirty list should have been resorted but was not.
I/flutter (26348): The list of dirty elements at the end of the buildScope call was:
I/flutter (26348):   Overlay-[LabeledGlobalKey<OverlayState>#ff44b]
I/flutter (26348):   AnimatedBuilder
I/flutter (26348):   AnimatedBuilder
I/flutter (26348):   SlideTransition
I/flutter (26348):   Scaffold
I/flutter (26348):   Material
I/flutter (26348):   AnimatedPhysicalModel
I/flutter (26348):   AnimatedDefaultTextStyle
I/flutter (26348):   _FloatingActionButtonTransition
I/flutter (26348):   Home
I/flutter (26348):   CustomDrawer
I/flutter (26348):   Material
I/flutter (26348):   AnimatedPhysicalModel
I/flutter (26348):   AnimatedDefaultTextStyle
I/flutter (26348):   Scrollable
I/flutter (26348):   GlowingOverscrollIndicator
I/flutter (26348):   AnimatedTextKit
I/flutter (26348):   AnimatedBuilder
I/flutter (26348):   GamePage-[<'Human-Ai'>]
I/flutter (26348):   Scaffold
I/flutter (26348):   Material
I/flutter (26348):   AnimatedPhysicalModel
I/flutter (26348):   AnimatedDefaultTextStyle
I/flutter (26348):   _FloatingActionButtonTransition
I/flutter (26348):   Material
I/flutter (26348):   AnimatedPhysicalModel
I/flutter (26348):   AnimatedDefaultTextStyle
I/flutter (26348):   _ToolbarItemWithIcon
I/flutter (26348):   _ToolbarItemWithIcon
I/flutter (26348):   _ToolbarItemWithIcon
I/flutter (26348):   _ToolbarItemWithIcon
I/flutter (26348):   Material
I/flutter (26348):   Material
I/flutter (26348):   Material
I/flutter (26348):   Material
I/flutter (26348):   _MaterialInterior
I/flutter (26348):   _MaterialInterior
I/flutter (26348):   _MaterialInterior
I/flutter (26348):   _MaterialInterior
I/flutter (26348):   Anim
I/flutter (26348): [2021-12-16 01:01:02.558601 | Catcher | INFO] buildScope missed some dirty elements.
I/flutter (26348): This probably indicates that the dirty list should have been resorted but was not.
I/flutter (26348): The list of dirty elements at the end of the buildScope call was:
I/flutter (26348):   Overlay-[LabeledGlobalKey<OverlayState>#ff44b]
I/flutter (26348):   AnimatedBuilder
I/flutter (26348):   AnimatedBuilder
I/flutter (26348):   SlideTransition
I/flutter (26348):   Scaffold
I/flutter (26348):   Material
I/flutter (26348):   AnimatedPhysicalModel
I/flutter (26348):   AnimatedDefaultTextStyle
I/flutter (26348):   _FloatingActionButtonTransition
I/flutter (26348):   Home
I/flutter (26348):   CustomDrawer
I/flutter (26348):   Material
I/flutter (26348):   AnimatedPhysicalModel
I/flutter (26348):   AnimatedDefaultTextStyle
I/flutter (26348):   Scrollable
I/flutter (26348):   GlowingOverscrollIndicator
I/flutter (26348):   AnimatedTextKit
I/flutter (26348):   AnimatedBuilder
I/flutter (26348):   GamePage-[<'Human-Ai'>]
I/flutter (26348):   Scaffold
I/flutter (26348):   Material
I/flutter (26348):   AnimatedPhysicalModel
I/flutter (26348):   AnimatedDefaultTextStyle
I/flutter (26348):   _FloatingActionButtonTransition
I/flutter (26348):   Material
I/flutter (26348):   AnimatedPhysicalModel
I/flutter (26348):   AnimatedDefaultTextStyle
I/flutter (26348):   _ToolbarItemWithIcon
I/flutter (26348):   _ToolbarItemWithIcon
I/flutter (26348):   _ToolbarItemWithIcon
I/flutter (26348):   _ToolbarItemWithIcon
I/flutter (26348):   Material
I/flutter (26348):   Material
I/flutter (26348):   Material
I/flutter (26348):   Material
I/flutter (26348):   _MaterialInterior
I/flutter (26348):   _MaterialInterior
I/flutter (26348):   _MaterialInterior
I/flutter (26348):   _MaterialInterior
I/flutter (26348):   Anim
I/flutter (26348): [2021-12-16 01:01:02.559072 | Catcher | INFO] 
I/flutter (26348): [2021-12-16 01:01:02.559072 | Catcher | INFO] 
I/flutter (26348): [2021-12-16 01:01:02.560020 | Catcher | INFO] ------- STACK TRACE -------
I/flutter (26348): [2021-12-16 01:01:02.560020 | Catcher | INFO] ------- STACK TRACE -------
I/flutter (26348): [2021-12-16 01:01:02.560462 | Catcher | INFO] #0      BuildOwner.buildScope.<anonymous closure> (package:flutter/src/widgets/framework.dart:2613:11)
I/flutter (26348): [2021-12-16 01:01:02.560462 | Catcher | INFO] #0      BuildOwner.buildScope.<anonymous closure> (package:flutter/src/widgets/framework.dart:2613:11)
I/flutter (26348): [2021-12-16 01:01:02.560656 | Catcher | INFO] #1      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:8)
I/flutter (26348): [2021-12-16 01:01:02.560656 | Catcher | INFO] #1      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:8)
I/flutter (26348): [2021-12-16 01:01:02.560842 | Catcher | INFO] #2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
I/flutter (26348): [2021-12-16 01:01:02.560842 | Catcher | INFO] #2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
I/flutter (26348): [2021-12-16 01:01:02.561025 | Catcher | INFO] #3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
I/flutter (26348): [2021-12-16 01:01:02.561025 | Catcher | INFO] #3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
I/flutter (26348): [2021-12-16 01:01:02.561223 | Catcher | INFO] #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
I/flutter (26348): [2021-12-16 01:01:02.561223 | Catcher | INFO] #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
I/flutter (26348): [2021-12-16 01:01:02.561394 | Catcher | INFO] #5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
I/flutter (26348): [2021-12-16 01:01:02.561394 | Catcher | INFO] #5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
I/flutter (26348): [2021-12-16 01:01:02.561616 | Catcher | INFO] #6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
I/flutter (26348): [2021-12-16 01:01:02.561616 | Catcher | INFO] #6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
I/flutter (26348): [2021-12-16 01:01:02.561808 | Catcher | INFO] #7      _rootRun (dart:async/zone.dart:1428:13)
I/flutter (26348): [2021-12-16 01:01:02.561808 | Catcher | INFO] #7      _rootRun (dart:async/zone.dart:1428:13)
I/flutter (26348): [2021-12-16 01:01:02.561982 | Catcher | INFO] #8      _CustomZone.run (dart:async/zone.dart:1328:19)
I/flutter (26348): [2021-12-16 01:01:02.561982 | Catcher | INFO] #8      _CustomZone.run (dart:async/zone.dart:1328:19)
I/flutter (26348): [2021-12-16 01:01:02.562151 | Catcher | INFO] #9      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
I/flutter (26348): [2021-12-16 01:01:02.562151 | Catcher | INFO] #9      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
I/flutter (26348): [2021-12-16 01:01:02.562347 | Catcher | INFO] #10     _invoke (dart:ui/hooks.dart:150:10)
I/flutter (26348): [2021-12-16 01:01:02.562347 | Catcher | INFO] #10     _invoke (dart:ui/hooks.dart:150:10)
I/flutter (26348): [2021-12-16 01:01:02.562527 | Catcher | INFO] #11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
I/flutter (26348): [2021-12-16 01:01:02.562527 | Catcher | INFO] #11     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
I/flutter (26348): [2021-12-16 01:01:02.562724 | Catcher | INFO] #12     _drawFrame (dart:ui/hooks.dart:114:31)
I/flutter (26348): [2021-12-16 01:01:02.562724 | Catcher | INFO] #12     _drawFrame (dart:ui/hooks.dart:114:31)
I/flutter (26348): [2021-12-16 01:01:02.562910 | Catcher | INFO] 
I/flutter (26348): [2021-12-16 01:01:02.562910 | Catcher | INFO] 
I/flutter (26348): [2021-12-16 01:01:02.563230 | Catcher | INFO] ======================================================================
I/flutter (26348): [2021-12-16 01:01:02.563230 | Catcher | INFO] ======================================================================
I/flutter (26348): [2021-12-16 01:01:02.578530 | Catcher | INFO] Creating mail request
I/flutter (26348): [2021-12-16 01:01:02.578530 | Catcher | INFO] Creating mail request
I/flutter (26348): [2021-12-16 01:01:02.588422 | Catcher | INFO] Report result: true
I/flutter (26348): [2021-12-16 01:01:02.588422 | Catcher | INFO] Report result: true
I/flutter (26348): [2021-12-16 01:01:02.625024 | Catcher | INFO] Opened file
I/flutter (26348): [2021-12-16 01:01:02.625024 | Catcher | INFO] Opened file
I/flutter (26348): [2021-12-16 01:01:02.626356 | Catcher | INFO] Writing report to file
I/flutter (26348): [2021-12-16 01:01:02.626356 | Catcher | INFO] Writing report to file
I/flutter (26348): [2021-12-16 01:01:02.691447 | Catcher | INFO] Closed file
I/flutter (26348): [2021-12-16 01:01:02.691447 | Catcher | INFO] Closed file
I/flutter (26348): [2021-12-16 01:01:02.691840 | Catcher | INFO] Report result: true
I/flutter (26348): [2021-12-16 01:01:02.691840 | Catcher | INFO] Report result: true
I/flutter (26348): [2021-12-16 01:01:07.599218 | Catcher | WARNING] Instance of 'EmailManualHandler' failed to report error because of timeout
I/flutter (26348): [2021-12-16 01:01:07.599218 | Catcher | WARNING] Instance of 'EmailManualHandler' failed to report error because of timeout
```

**Comment by Leptopoda** [comment]
without any steps to reproduce this information is just not possible to debug

**Comment by calcitem** [comment]
I recorded it as a memo first. If I find a way to reproduce it, I will assign it and add more information.
