### ISSUE TITLE
Exception: HiveImpl._openBox (hive_impl.dart:117): type 'Null' is not a subtype of type 'double' in type cast

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#474]
Commit 71248fc8

Run debug:

```
HiveImpl._openBox (hive_impl.dart:117)
<asynchronous gap>
HiveImpl.openBox (hive_impl.dart:139)
<asynchronous gap>
LocalDatabaseService._initDisplay (storage.dart:119)
<asynchronous gap>
LocalDatabaseService.initStorage (storage.dart:80)
<asynchronous gap>
main (main.dart:53)
<asynchronous gap>
```

```
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
Debug service listening on ws://127.0.0.1:64288/-dymcb4E-U0=/ws
Syncing files to device Windows...
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'double' in type cast
#0      DisplayAdapter.read (package:sanmill/models/display.g.dart:98:30)
#1      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:326:33)
#2      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:274:26)
#3      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21:26)
#4      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42:12)
<asynchronous suspension>
#5      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86:11)
<asynchronous suspension>
#6      HiveImpl._openBox (package:hive/src/hive_impl.dart:111:9)
<asynchronous suspension>
#7      HiveImpl.openBox (package:hive/src/hive_impl.dart:139:12)
<asynchronous suspension>
#8      LocalDatabaseService._initDisplay (package:sanmill/services/storage/storage.dart:119:19)
<asynchronous suspension>
#9      LocalDatabaseService.initStorage (package:sanmill/services/storage/storage.dart:80:5)
<asynchronous suspension>
#10     main (package:sanmill/main.dart:53:3)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'double' in type cast
#0      DisplayAdapter.read (package:sanmill/models/display.g.dart:98:30)
#1      BinaryReaderImpl.read (package:hive/src/binary/binary_reader_impl.dart:326:33)
#2      BinaryReaderImpl.readFrame (package:hive/src/binary/binary_reader_impl.dart:274:26)
#3      FrameHelper.framesFromBytes (package:hive/src/binary/frame_helper.dart:21:26)
#4      FrameIoHelper.framesFromFile (package:hive/src/io/frame_io_helper.dart:42:12)
<asynchronous suspension>
#5      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:86:11)
<asynchronous suspension>
#6      HiveImpl._openBox (package:hive/src/hive_impl.dart:111:9)
<asynchronous suspension>
#7      HiveImpl.openBox (package:hive/src/hive_impl.dart:139:12)
<asynchronous suspension>
#8      LocalDatabaseService._initDisplay (package:sanmill/services/storage/storage.dart:119:19)
<asynchronous suspension>
#9      LocalDatabaseService.initStorage (package:sanmill/services/storage/storage.dart:80:5)
<asynchronous suspension>
#10     main (package:sanmill/main.dart:53:3)
<asynchronous suspension>
```

**Comment by Leptopoda** [comment]
Have you made shure tht you actually ran buildrunner before the build?

**Comment by Leptopoda** [comment]
Also please keep in mind that now that the db is in a degraded state It might happen that necessary migrations won't be run, even if you recompile with the latest generated assets.

Also the migration service has been build in a way that the device will keep track of the current db version and only run the migrations if a never version is needed/available. You might have checked out a commit from a PR which ran some migrations, and marked the db as migrated by setting the version to the latest. I then added further migrations that will eventually count to the same migration process (because it is going to be in the same apk version later on) but your phone now won't run them because it doesn't know of the new changes. 

This is a problem when jumping between versions :upside_down_face: and this shouldn't happen in production. Nevertheless covering the migration service in unit tests is very high on my todo as it braking would bring the entire app to a halt.

**Comment by calcitem** [comment]
Understood. Every time I install a new apk, I will uninstall it first. Regression validation of the migration will be done before the 2.0 release.

**Comment by calcitem** [comment]
The problem did not reproduce.
