### ISSUE TITLE
E/flutter (23084): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: LateInitializationError: Field 

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#554]
Install old version, and install new.

```
E/flutter (23084): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: LateInitializationError: Field '_currentVersion@1153470052' has already been initialized.
E/flutter (23084): #0      LateError._throwFieldAlreadyInitialized (dart:_internal-patch/internal_patch.dart:201:5)
E/flutter (23084): #1      _DatabaseMigration._currentVersion= (package:sanmill/services/database/database_migration.dart:47:26)
E/flutter (23084): #2      _DatabaseMigration.migrate (package:sanmill/services/database/database_migration.dart:77:9)
E/flutter (23084): <asynchronous suspension>
E/flutter (23084): #3      Database.init (package:sanmill/services/database/database.dart:99:5)
E/flutter (23084): <asynchronous suspension>
E/flutter (23084): #4      main (package:sanmill/main.dart:52:3)
E/flutter (23084): <asynchronous suspension>
E/flutter (23084): 
```

**Comment by calcitem** [comment]
I am not sure if https://github.com/calcitem/Sanmill/commit/1fe6fb5aface397559a91ff996ae7aceaa2d33e5 is right.

**Comment by Leptopoda** [comment]
Does this issue also occur in production? I can only imagine this being a problem when using hot reload so this shouldn't be a problem.


In general late final is a bit problematic with hot reload and removing the final won't be a problem. 🙃

I just saw the diff on my phone so I could be mistaken. I hope I don't forget having a look on my pc later.

**Comment by calcitem** [comment]
> Does this issue also occur in production

Not test yet.

> hot reload?

Yes!
