### ISSUE TITLE
Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#576]
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4241:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4255:6)
#2      Element.dependOnInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4275:12)
#3      Localizations.of (package:flutter/src/widgets/localizations.dart:472:48)
#4      S.of (package:sanmill/generated/intl/l10n.dart:110:26)
#5      _BoardState.build.<anonymous closure>.<anonymous closure> (package:sanmill/screens/game_page/board.dart:111:34)
<asynchronous suspension>
```

**Comment by calcitem** [comment]
```
              final strTimeout = S.of(context).timeout;
              final strNoBestMoveErr = S.of(context).error("No best move");
```

Maybe can fix it.
