### ISSUE TITLE
snap error

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#743]
```text
/snap/mill/x1/usr/local/bin/mill: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /snap/mill/x1/usr/local/bin/mill)
/snap/mill/x1/usr/local/bin/mill: /snap/mill/x1/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /snap/mill/x1/usr/local/bin/mill)
```

**Comment by calcitem** [comment]
```
$ flutter build linux --release

] [   +1 ms] kernel_snapshot: Starting due to {}                                                                                                                                                      
:: [   +2 ms] [  +14 ms] /root/parts/mill/build/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev /root/parts/mill/build/flutter/bin/cache/dart-sdk/bin/snapshots/frontend_server.dart.snapshot --sdk-root /root/parts/mill/build/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/ --target=flutter --no-print-incremental-dependencies -Ddart.vm.profile=false -Ddart.vm.product=true --aot --tfa --target-os linux --packages /root/parts/mill/build/src/ui/flutter_app/.dart_tool/package_config.json --output-dill /root/parts/mill/build/src/ui/flutter_app/.dart_tool/flutter_build/175d66044810baccd579bec1db623caa/app.dill --depfile /root/parts/mill/build/src/ui/flutter_app/.dart_tool/flutter_build/175d66044810baccd579bec1db623caa/ker
nel_snapshot.d --source file:///root/parts/mill/build/src/ui/flutter_app/.dart_tool/flutter_build/dart_plugin_registrant.dart --source package:flutter/src/dart_plugin_registrant.dart -Dflutter.dart_plugin_registrant=file:///root/parts/mill/build/src/ui/flutter_app/.dart_tool/flutter_build/dart_plugin_registrant.dart --verbosity=error package:sanmill/main.dart                                                                                                                                                        
:: [        ] [+55991 ms] Persisting file store                                                                                                                                                                   
:: [        ] [  +36 ms] Done persisting file store                                                                                                                                                               
:: [        ] [   +8 ms] Target kernel_snapshot failed: Exception                                                                                                                                                 
:: [        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:256:7)                                                                                          
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:853:9)                                                                                  
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)                                                                                                                  
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)                                                                                    
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)                                                                                                                  
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)                                                                                    
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #6      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)                                                                                                                  
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #7      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:791:32)                                                                                    
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #8      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:620:16)                                                                                       
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #9      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:315:32)                                                                                             
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)                                                                           
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)                                                                                          
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #12     CommandRunner.runCommand (package:args/command_runner.dart:212:13)                                                                                                               
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)                                                         
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)                                                                                          
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #15     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)                                                                             
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)                                                                                            
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)                                                                                          
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #18     main (package:flutter_tools/executable.dart:90:3)                                                                                                                                
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ] [  +64 ms] "flutter assemble" took 58,211ms.                                                                                                                                                        
:: [        ] [  +12 ms]                                                                                                                                                                                          
:: [        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)                                                                                                                  
:: [        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:332:7)                                                                                              
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)                                                                           
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)                                                                                          
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)                                                                                                               
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)                                                         
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)                                                                                          
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)                                                                             
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)                                                                                            
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)                                                                                          
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ]            #10     main (package:flutter_tools/executable.dart:90:3)                                                                                                                                
:: [        ]            <asynchronous suspension>                                                                                                                                                                
:: [        ] [  +29 ms] Running 0 shutdown hooks                                                                                                                                                                 
:: [        ] [        ] Shutdown hooks complete                                                                                                                                                                  
:: [        ] [   +2 ms] exiting with code 1                                                                                                                                                                      
:: [        ] ninja: build stopped: subcommand failed.                                                                                                                                                            
:: [  +26 ms] Building Linux application... (completed in 62.4s)                                                                                                                                                  
:: [   +2 ms] "flutter linux" took 66,187ms.                                                                                                                                                                      
:: [   +5 ms] Build process failed                                                                                                                                                                                
:: [   +2 ms]                                                                                                                                                                                                     
::            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)                                                                                                                             
::            #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:181:5)                                                                                                                          
::            <asynchronous suspension>                                                                                                                                                                           
::            #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:75:5)                                                                                                                          
::            <asynchronous suspension>                                                                                                                                                                           
::            #3      BuildLinuxCommand.runCommand (package:flutter_tools/src/commands/build_linux.dart:86:5)                                                                                                     
::            <asynchronous suspension>                                                                                                                                                                           
::            #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1297:27)                                                                                      
::            <asynchronous suspension>                                                                                                                                                                           
::            #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)                                                                                                     
::            <asynchronous suspension>                                                                                                                                                                           
::            #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)                                                                                                                          
::            <asynchronous suspension>                                                                                                                                                                           
::            #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:9)                                                                    
::            <asynchronous suspension>                                                                                                                                                                           
::            #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)                                                                                                     
::            <asynchronous suspension>                                                                                                                                                                           
::            #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:285:5)                                                                                        
::            <asynchronous suspension>                                                                                                                                                                           
::            #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:115:9)                                                                                                       
::            <asynchronous suspension>                                                                                                                                                                           
::            #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)                                                                                                     
::            <asynchronous suspension>                                                                                                                                                                           
::            #12     main (package:flutter_tools/executable.dart:90:3)                                                                                                                                           
::            <asynchronous suspension>                                                                                                                                                                           
::                                                                                                                                                                                                                
::                                                                                                                                                                                                                
:: [   +8 ms] Running 0 shutdown hooks                                                                                                                                                                            
:: [        ] Shutdown hooks complete                                                                                                                                                                             
:: [        ] exiting with code 1                                                                                                                                                                                 
'override-build' in part 'mill' failed with code 1.
```
