### ISSUE TITLE
bool Position::put_piece(Square, bool): assertion "false" failed

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#796]
```
SkillLevel = 14
MoveTime = 0
Algorithm = 2
UsePerfectDatabase = false
PerfectDatabasePath = /Users/phoebus/Library/Containers/A1A7A2BE-2307-44D4-B044-F9D07ED5DAD7/Data/Documents/strong
DrawOnHumanExperience = true
ConsiderMobility = true
AiIsLazy = false
Shuffling = false
DeveloperMode = false
PiecesCount = 11
HasDiagonalLines = false
NMoveRule = 30
EndgameNMoveRule = 100
ThreefoldRepetitionRule = false
PiecesAtLeastCount = 3
BoardFullAction = 3
MillFormationActionInPlacingPhase = 2
MayMoveInPlacingPhase = false
IsDefenderMoveFirst = true
StalemateAction = 0
MayFly = true
FlyPieceCount = 3
MayRemoveFromMillsAlways = false
MayRemoveMultiple = true

```

```
 1.    a4    g1
 2.    d3    e3
 3.    g4    c4
 4.    e4    f2
 5.    g7    b6
 6.    a1
```

and tap `f4`. crash

```
D/MillEngine(14108): [uci] input: position fen ********/********/******** w p p 0 11 0 11 0 0 0 1 moves (3,7) (3,4) (1,5) (1,4) (3,3) (1,7) (1,3) (2,4) (3,2) (2,8) (1,6) (2,3) 
I/flutter (14108): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (14108): │ #0   Engine._send (package:sanmill/game_page/services/engine/engine.dart:45:12)
I/flutter (14108): │ #1   Engine.search (package:sanmill/game_page/services/engine/engine.dart:126:13)
I/flutter (14108): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (14108): │ [engine] send: go
I/flutter (14108): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/MillEngine(14108): [uci] input: go
F/libc    (14108): /Users/phoebus/Sanmill/src/position.cpp:711: bool Position::put_piece(Square, bool): assertion "false" failed
```

**Comment by calcitem** [comment]
cannot preduct

**Comment by calcitem** [comment]
but uninstall and resinstall cannot reproduce.

**Comment by calcitem** [comment]
because of setup postion is not perfect.
