### ISSUE TITLE
Unexpected engine response: info score 1 bestmove (3,1)->(3,2)

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#884]
```
I/flutter (23571): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (23571): │ #0   Engine.search (package:sanmill/game_page/services/engine/engine.dart:161:14)
I/flutter (23571): │ #1   <asynchronous suspension>
I/flutter (23571): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (23571): │ 💡 FEN = @*@*@O@O/O*O@O*O@/@*O*@O@O b m s 9 0 9 0 0 0 0 0 0 0 0 0 10
I/flutter (23571): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/MillEngine(23571): [uci] input: setoption name MoveTime value 1
D/MillEngine(23571): [uci] input: position fen ********/********/******** w p p 0 9 0 9 0 0 0 0 0 0 0 0 1 moves (2,1) (2,4) (2,7) (2,8) (2,5) (3,1) (2,3) (1,5) (1,8) (3,5) (3,6) (1,3) (3,8) (3,7) (3,2) (1,7) (1,6) (1,1) (3,2)->(3,3) 
D/MillEngine(23571): [uci] input: setoption name Algorithm value 2
D/MillEngine(23571): [uci] input: go
D/MillEngine(23571): [uci] input: setoption name UsePerfectDatabase value false
D/MillEngine(23571): println: info score 1 bestmove (3,1)->(3,2)
D/MillEngine(23571): [uci] input: setoption name PerfectDatabasePath value /storage/emulated/0/Android/data/com.calcitem.sanmill/files/strong
D/MillEngine(23571): [uci] input: setoption name DrawOnHumanExperience value true
D/MillEngine(23571): [uci] input: setoption name ConsiderMobility value true
D/MillEngine(23571): [uci] input: setoption name FocusOnBlockingPaths value false
D/MillEngine(23571): [uci] input: setoption name AiIsLazy value false
D/MillEngine(23571): [uci] input: setoption name Shuffling value true
D/MillEngine(23571): [uci] input: setoption name DeveloperMode value false
D/MillEngine(23571): [uci] input: setoption name PiecesCount value 9
D/MillEngine(23571): [uci] input: setoption name HasDiagonalLines value false
D/MillEngine(23571): [uci] input: setoption name NMoveRule value 100
D/MillEngine(23571): [uci] input: setoption name EndgameNMoveRule value 100
D/MillEngine(23571): [uci] input: setoption name ThreefoldRepetitionRule value true
D/MillEngine(23571): [uci] input: setoption name PiecesAtLeastCount value 3
D/MillEngine(23571): [uci] input: setoption name BoardFullAction value 0
D/MillEngine(23571): [uci] input: setoption name MillFormationActionInPlacingPhase value 0
D/MillEngine(23571): [uci] input: setoption name MayMoveInPlacingPhase value false
D/MillEngine(23571): [uci] input: setoption name IsDefenderMoveFirst value false
D/MillEngine(23571): [uci] input: setoption name RestrictRepeatedMillsFormation value false
D/MillEngine(23571): [uci] input: setoption name StalemateAction value 0
D/MillEngine(23571): [uci] input: setoption name MayFly value true
D/MillEngine(23571): [uci] input: setoption name FlyPieceCount value 3
D/MillEngine(23571): [uci] input: setoption name MayRemoveFromMillsAlways value false
D/MillEngine(23571): [uci] input: setoption name MayRemoveMultiple value false
D/MillEngine(23571): [uci] input: setoption name OneTimeUseMill value false
D/MillEngine(23571): [uci] input: quit
D/MillEngine(23571): println: uciok
I/flutter (23571): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (23571): │ #0   Engine._waitResponse (package:sanmill/game_page/services/engine/engine.dart:317:20)
I/flutter (23571): │ #1   <asynchronous suspension>
I/flutter (23571): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (23571): │ ⚠️ [engine] Unexpected engine response: info score 1 bestmove (3,1)->(3,2)
I/flutter (23571): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/MillEngine(23571): [uci] input: uci
I/flutter (23571): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (23571): │ #0   Engine._waitResponse (package:sanmill/game_page/services/engine/engine.dart:317:20)
I/flutter (23571): │ #1   <asynchronous suspension>
I/flutter (23571): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (23571): │ ⚠️ [engine] Unexpected engine response: uciok
I/flutter (23571): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (23571): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (23571): │ #0   Engine._waitResponse (package:sanmill/game_page/services/engine/engine.dart:317:20)
I/flutter (23571): │ #1   <asynchronous suspension>
I/flutter (23571): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (23571): │ ⚠️ [engine] Unexpected engine response: uciok
I/flutter (23571): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (23571): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (23571): │ #0   GameController.engineToGo (package:sanmill/game_page/services/controller/game_controller.dart:289:16)
I/flutter (23571): │ #1   <asynchronous suspension>
I/flutter (23571): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (23571): │ 💡 [engineToGo] Engine response type: timeout
```

**Comment by calcitem** [comment]
1.    d6    f2
 2.    b4    b6
 3.    d2    d7
 4.    f4    d3
 5.    c5    d1
 6.    a1    e4
 7.    a7    a4
 8.    g7    c4
 9.    c3    d5
10.    g7-g4
